baseURL = "your_domain"
languageCode = "en-us"
title = "Your site title"
theme = "hugo-lamp"
googleAnalytics = "UA-XXXXXXXX-X"                             # Google Analytics UA number

[params]
  subtitle = "Light responsive AMP theme"
  author = "Your name"
  avatar = "/img/avatar.jpg"
  description = "A light responsive Hugo AMP theme for blogger"
  paginate = 10

  # Google Adsense
  adsensePublisher = "ca-pub-XXX"
  adsenseSlot = "XXX"

  # SEO configs
  seotitle = "Hugo Blog Title (SEO Version)"
  googleSiteVerification = "google_site_verification_code"    # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

  # Social networks
  email = "name@domain.com"
  github = "github_username"
  twitter = "twitter_username"
  linkedin = "linkedin_username"
  facebook = "facebook_username"
  google = "googleplus_id_number"
  instagram = "instagram_username"
  youtube = "youtube_username"
  dribbble = "dribbble_username"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Hugo"
  weight = 1
  identifier = "hugo"
  url = "/hugo/"
[[menu.main]]
  name = "AMP Project"
  weight = 2
  identifier = "amp"
  url = "/amp/"
[[menu.main]]
  name = "Tags"
  weight = 3
  identifier = "tags"
  url = "/tags/"
